"""
PROJECT: ASHEN OATH
MODULE: RESONANCE BARREL GENERATOR (UMB-TECH-BARREL-001)
AUTHOR: ANTIGRAVITY ARCHITECT
DESCRIPTION:
    Walks the project directory and generates MANIFEST.md files
    for each subdirectory containing GVRN-compliant scripts.
"""

import os
import re

# Refined Regex for GVRN Metadata extraction
# Supports both """ [GVRN] """ and # [GVRN] comment blocks
GVRN_BLOCK_PATTERN = re.compile(r'(?:"""|#)\s*\[GVRN\].*?(?:\s*"""|\n\n)', re.DOTALL)
ARTIFACT_ID_PATTERN = re.compile(r'Artifact ID:\s*([^\n]+)')
DESCRIPTION_PATTERN = re.compile(r'Description:\s*([^\n]+)')

BLACK_LIST = [".agent", ".trunk", ".git", ".godot", "addons", "node_modules"]

def extract_gvrn_metadata(filepath):
    """Parses a .gd file to extract Sovereign metadata."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read(4096)
            
            # Find the GVRN block
            block_match = GVRN_BLOCK_PATTERN.search(content)
            if not block_match:
                return None
            
            header = block_match.group(0)
            # Remove comment hashes if it's a comment-based header
            header = re.sub(r'^#\s*', '', header, flags=re.MULTILINE)
            
            artifact_id = ARTIFACT_ID_PATTERN.search(header)
            description = DESCRIPTION_PATTERN.search(header)
            
            if not artifact_id:
                return None
                
            return {
                "id": artifact_id.group(1).strip(),
                "desc": description.group(1).strip() if description else "No description provided.",
                "file": os.path.basename(filepath)
            }
    except Exception as e:
        print(f"Error parsing {filepath}: {e}")
    return None

def generate_manifest(directory, metadata_list):
    """Creates a MANIFEST.md in the target directory with aligned formatting."""
    if not metadata_list:
        return
    
    manifest_path = os.path.join(directory, "MANIFEST.md")
    print(f"Sealing Resonance Barrel: {manifest_path}")
    
    # Calculate column widths for alignment
    id_width = max(len(m['id']) + 2 for m in metadata_list)
    id_width = max(id_width, 18)
    
    desc_width = max(len(m['desc']) for m in metadata_list)
    desc_width = max(desc_width, 40)
    
    src_width = max(len(m['file']) + 12 for m in metadata_list)
    src_width = max(src_width, 40)
    
    with open(manifest_path, 'w', encoding='utf-8') as f:
        f.write(fr"\# RESONANCE BARREL: {os.path.basename(directory).upper()}\n\n")
        f.write("## Active Artifacts\n\n")
        
        # Header
        f.write(f"| {'Artifact ID':<{id_width}} | {'Description':<{desc_width}} | {'Source':<{src_width}} |\n")
        f.write(f"| :{'-'*(id_width-1)} | :{'-'*(desc_width-1)} | :{'-'*(src_width-1)} |\n")
        
        for m in sorted(metadata_list, key=lambda x: x['id']):
            id_str = f"`{m['id']}`"
            src_str = f"[{m['file']}](./{m['file']})"
            f.write(f"| {id_str:<{id_width}} | {m['desc']:<{desc_width}} | {src_str:<{src_width}} |\n")
        
        f.write(f"\n---\n\n_Generated by Sovereign Resonance Barrel Tool v1.0_\n")

def walk_and_barrel(root_dir):
    """Walks the directory and triggers manifest generation."""
    for root, dirs, files in os.walk(root_dir):
        # Apply Blacklist
        dirs[:] = [d for d in dirs if not d.startswith('.') and d not in BLACK_LIST]
        
        gd_files = [f for f in files if f.endswith('.gd')]
        if not gd_files:
            continue
            
        metadata_batch = []
        for gd in gd_files:
            meta = extract_gvrn_metadata(os.path.join(root, gd))
            if meta:
                metadata_batch.append(meta)
        
        if metadata_batch:
            generate_manifest(root, metadata_batch)

def find_project_root(start_path):
    """Climbs the directory tree to find project.godot."""
    current = start_path
    while True:
        if os.path.exists(os.path.join(current, "project.godot")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return start_path
        current = parent

if __name__ == "__main__":
    PROJECT_ROOT = find_project_root(os.getcwd())
    print(f"Initiating Resonance Sweep in: {PROJECT_ROOT}")
    
    # Sweep through logic and scene domains
    domains = ['scripts', 'scenes']
    for domain in domains:
        path = os.path.join(PROJECT_ROOT, domain)
        if os.path.exists(path):
            walk_and_barrel(path)
    
    print("\nResonance Sweep Complete. Barrels sealed.")

